spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db?currentSchema=public,reWriteBatchedInserts=true
    username: postgres
    password: root
    hikari:
      connectionTimeout: 300000 #5 minutes
      maximumPoolSize: 10
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        order_updates: true
        jdbc.batch_size: 50
        order_inserts: true
        generate_statistics: true
        batch_versioned_data: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
#    org.hibernate.SQL: DEBUG
 #   org.hibernate.type.descriptor.sql.BasicBinder: TRACE